services:
  myfashiontrunk-app:
    image: 'rhoopoe/myfashiontrunk:latest'
    build:
      dockerfile: ./Dockerfile
    container_name: myfashiontrunk-app
    depends_on:
      - myfashiontrunk-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://myfashiontrunk-db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - AWS_REGION=eu-central-1
    ports:
      - "8080:8080"
    volumes:
      - /home/rick/.aws:/root/.aws
  myfashiontrunk-db:
    image: 'postgres:15-alpine'
    container_name: myfashiontrunk-db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres