logging: level:DEBUG
spring:
  datasource:
    password: jIOHohfdoiHIAD445_jds#LLd
    url: jdbc:postgresql://localhost:5432/myfashiontrunk
    username: rhoopoe
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 2MB
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
app:
  image-bucket: allowed-item-images
  min-detection-confidence: 75
  max-detected-labels: 10
